Update sync-repos.yml

diff --git a/.github/workflows/sync-repos.yml b/.github/workflows/sync-repos.yml
--- a/.github/workflows/sync-repos.yml
+++ b/.github/workflows/sync-repos.yml
@@ -1,3 +1,4 @@
+
 name: Azure DevOps Repo Sync
 
 on:
@@ -32,8 +33,8 @@ jobs:
 
       - name: Install Required Packages
         run: |
-          sudo apt update
-          sudo apt install -y jq gh
+          sudo apt-get update
+          sudo apt-get install -y jq gh
 
       - name: Configure Git
         run: |
@@ -70,13 +71,17 @@ jobs:
           echo "GITHUB AUTH TEST"
           echo "========================================"
 
-          echo "$GH_TOKEN" | gh auth login --with-token
-          gh auth status
+          gh auth status || true
 
-          ENCODED_PROJECT=$(printf '%s' "$AZURE_PROJECT" | jq -sRr @uri)
+          echo "GitHub User:"
+          gh api user --jq .login || true
 
           echo ""
-          echo "Encoded Project: $ENCODED_PROJECT"
+          echo "========================================"
+          echo "FETCHING AZURE REPOSITORIES"
+          echo "========================================"
+
+          ENCODED_PROJECT=$(printf '%s' "$AZURE_PROJECT" | jq -sRr @uri)
 
           RESPONSE=$(curl -s \
             -u :$AZURE_PAT \
@@ -92,7 +97,7 @@ jobs:
           cat repos.json
 
           if ! jq -e '.value' repos.json >/dev/null 2>&1; then
-            echo "Azure API returned an error"
+            echo "Azure API Error"
             cat repos.json
             exit 1
           fi
@@ -105,7 +110,7 @@ jobs:
           echo "========================================"
 
           if [ "$REPO_COUNT" -eq 0 ]; then
-            echo "No repositories found"
+            echo "No repositories found."
             exit 1
           fi
 
@@ -117,6 +122,7 @@ jobs:
 
           while IFS= read -r repoJson
           do
+
             echo ""
             echo "========================================"
 
@@ -130,7 +136,7 @@ jobs:
             MIRROR_PATH="mirrors/$SAFE_NAME.git"
 
             AUTH_CLONE_URL=$(echo "$REMOTE_URL" | \
-              sed "s#https://#https://:$AZURE_PAT@#")
+              sed "s#https://#https://user:$AZURE_PAT@#")
 
             if [ -d "$MIRROR_PATH" ]; then
 
@@ -164,10 +170,11 @@ jobs:
 
             if ! gh repo view "$GH_USERNAME/$REPO_NAME" >/dev/null 2>&1; then
 
-              echo "GitHub Repository Not Found"
+              echo "Repository Not Found. Creating..."
 
               gh repo create "$GH_USERNAME/$REPO_NAME" \
-                --private
+                --private \
+                --confirm
 
               echo "Repository Created"
 
